### ISSUE TITLE
user admin

### ISSUE THREAD

**Issue by juminto** [akhwan90/rapor2013#1]
password user adminya apa yah?

**Comment by zevidalifa** [comment]
password untuk adminnya apa ya ?

**Comment by ahmadpaiz** [comment]
alhamdulilah password admin super90 tapi kenapa balik ke menu ya.... n saya coba guru juga demikian ....terima kasih sebelumnya

**Comment by izzul28** [comment]
kok gak ada efek gan

**Comment by shan89s** [comment]
aplikasi berjalan dengan baik di xampp versi 5.6... selamat mencoba

**Comment by akhwan90** [comment]
ntap, gan @juminto @ahmadpaiz @izzul28 @shan89s

**Comment by adighoro13** [comment]
password user adminya apa yah?
