### ISSUE TITLE
data mapel

### ISSUE THREAD

**Issue by PancaBhakti89** [akhwan90/rapor2013#10]
gan kenapa mapel nya tidak bisa disimpan...?

**Comment by projecttrinof** [comment]
Cek Pada File Data_Mapel.php baris 75 dan Edit, Seharusnya jadi seperti ini :
`$this->db->query("INSERT INTO m_mapel (kelompok, nama, kd_singkat) VALUES ('".$p['kelompok']."','".$p['nama']."', '".$p['kd_singkat']."')");`

**Comment by PancaBhakti89** [comment]
Ok gan terima kasih. kemarin udh bisa diperbaiki. ad problem lain lagi gan. KD nya gak bisa ditambah.

**Comment by projecttrinof** [comment]
Apa Keterangan Errornya gan?

**Comment by PancaBhakti89** [comment]
Berhasil Disimpan, Tapi KD ny gak muncul. apa kode nye ad struktur tersendiri gan.

**Comment by projecttrinof** [comment]
Sebenarnya ini bukan project saya, tapi saya hanya membantu jawab saja.
Saya telah mencobanya di localhost maupun hosting. untuk simpan dan menampilkan KD normal gan.

**Comment by akhwan90** [comment]
terimakasih gan @projecttrinof , akan segera saya merge-kan.. hehehe
