### ISSUE TITLE
Beberapa Bug pada App

### ISSUE THREAD

**Issue by arie86** [akhwan90/rapor2013#3]
aplikasinya sudah keren dan friendly, tapi masih ada beberapa bug nih bos.
1. Set Kelas (admin) siswa gak tampil pada preview kelas yang telah di tentukan
2. Set Wali Kelas, pada menu admin masuk, tapi pada login guru yang bersangkutan tidak terdeteksi kalau jadi wali kelas
3. Mapel diampu (guru) klau nilai input manual sukses tapi kalau lewat upload excel error, dan jika ingin print nilai yg tampil di siswa yang sudah agan set pada contoh (bawaan), tapi kalau siswa yang kita set baru pada set kelas (admin) tidak tampil jika kita ingin print.
4. Login Siswa pada raport (S4) Tempat tgl Lahir Error tampilannya... 

kalau bisa, di menu input baik guru, siswa, ataupun mapel ada menu hapus gan....

**Comment by shark1313** [comment]
Udah fix belum bro ? soalnya upload biodata siswa via excel juga nggak bisa

**Comment by akhwan90** [comment]
ok, gan, ntar habis isya' ane update...
