### ISSUE TITLE
tidak berfungsi di xampp 7.2.5

### ISSUE THREAD

**Issue by yudistirairvan** [akhwan90/rapor2013#4]
saya pake xampp versi 7.2.5 saat login halaman tidak ke rederect ke home melainkan ke login lagi

**Comment by akhwan90** [comment]
oya, memang ada permasalahan di PHP versi terbaru, bos.. tunggu release update..

**Comment by akhwan90** [comment]
https://github.com/akhwan90/rapor2013/commit/c8758c66795b1a42284f31aa4b7897b17a031260

**Comment by akhwan90** [comment]
https://github.com/akhwan90/rapor2013/releases
