### ISSUE TITLE
Tidak bisa tambah data mapel

### ISSUE THREAD

**Issue by Firdaus17** [akhwan90/rapor2013#5]
Gan, kenapa ya pas tambah data mapel tidak ada respon apapun dari program.

**Comment by Firdaus17** [comment]
Dan pas set kelas, siswa yg ditambahkan tidak muncul di kolom kelasnya

**Comment by naufalhumam** [comment]
ini kenapa banyak error ya gan? halaman login pun belum bisa

A PHP Error was encountered
Severity: 8192

Message: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

Filename: MX/Router.php

Line Number: 239

Backtrace:

File: C:\xampp\htdocs\rapor2013-master\application\third_party\MX\Router.php
Line: 239
Function: strpos

File: C:\xampp\htdocs\rapor2013-master\application\third_party\MX\Router.php
Line: 101
Function: _set_default_controller

File: C:\xampp\htdocs\rapor2013-master\index.php
Line: 317
Function: require_once

**Comment by akhwan90** [comment]
Update ke release terbaru, yg support php7 gan..
