### ISSUE TITLE
Tidal work di Xampp 7.3.5

### ISSUE THREAD

**Issue by bilirenaldi** [akhwan90/rapor2013#6]
Tidak bisa login di xampp versi 7.3.5 , saat login tidak bisa redirect ke halaman home

**Comment by aldipay21** [comment]
> Tidak bisa login di xampp versi 7.3.5 , saat login tidak bisa redirect ke halaman home

bisa tapi yang php 5 gan

**Comment by akhwan90** [comment]
Update support PHP 7 https://github.com/akhwan90/rapor2013/commit/c8758c66795b1a42284f31aa4b7897b17a031260
